# Etapa de construcción
FROM golang:1.22.6 AS builder
WORKDIR /app

# Copiamos los archivos de dependencias primero
COPY ProyectoParcial1Go/go.mod .
COPY ProyectoParcial1Go/go.sum .
RUN go mod download

# Copiamos el resto del código
COPY . .

# Instalamos las dependencias
RUN go mod tidy

# Compilamos el proyecto, indicando el archivo fuente principal y el nombre de salida del binario
RUN go build -o main ./ProyectoParcial1Go/cmd/server/main.go

# Etapa final
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .

CMD ["./main"]