# Usa una imagen base con la versión más reciente de Go
FROM golang:latest

# Crea el directorio de trabajo
RUN mkdir -p /app
WORKDIR /app

# Instala make y gcc para compilar
RUN apt-get update && \
    apt-get install -y make gcc

# Copia los archivos go.mod y go.sum para gestionar dependencias
COPY go.mod go.sum ./

# Descarga las dependencias (esto se puede aprovechar para optimizar el caché)
RUN go mod download

# Copia todo el código al contenedor
COPY . .

# Ejecuta las pruebas directamente sin necesidad de compilar un binario
CMD ["go", "test", "-v", "./..."]

RUN makefile -f dockerfile