# Usa una imagen base con la versión de Go que necesitas
FROM golang:1.23.1-alpine

# Configura el directorio de trabajo
WORKDIR /app

# Copia los archivos go.mod y go.sum
COPY go.mod . 
COPY go.sum .

# Descarga las dependencias
RUN go mod download

# Copia el resto del código
COPY . .

# Compila las pruebas
RUN go test -c -o server.test ./server/Server_test.go

# Copia el archivo ejecutable de las pruebas al contenedor
COPY server.test .

# Ejecuta las pruebas
CMD ["./server.test", "-test.v"]